version: '3.9'

services:
  
  postgres:
    image: postgres:16
    container_name: posey_postgres
    environment:
      POSTGRES_DB: posey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./posey_data:/docker-entrypoint-initdb.d:ro       
    restart: unless-stopped

 
  adminer:
    image: adminer
    container_name: posey_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg_data: